server:
  port: 8080

---

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: emailotpverificationdb

#Gmail Server message configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: ngnawens@gmail.com
    password: vmhlpwmwwjwrwmnb #Password generated when the multi-authenticator is configured on your Server Messager
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true