server:
  port: 8080

---

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: emailotpverificationdb

#Gmail Server message configuration
#Added the line below in your configuration VM and make sure to specify the rigth username and password
#MAIL_HOST=smtp.gmail.com;MAIL_PORT=587;MAIL_USERNAME=Your username;MAIL_PASSWORD=Your password
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME} #Sender email
    password: ${MAIL_PASSWORD} # sender password
    protocol: smtp

